CREATE TABLE warehouses
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    warehouse_name character varying(255) COLLATE pg_catalog."default",
    div_num integer,
    CONSTRAINT warehouses_pkey PRIMARY KEY (id),
    CONSTRAINT div_num FOREIGN KEY (div_num)
        REFERENCES public.divisions (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)